version: "3.3"

services:
  blogsMcFateM:
    image: mcfatem/blogs-mcfatem
    container_name: blogsMcFateM
    networks:
      - proxy
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.blog.rule: "Host(`${HOST}`) && PathPrefix(`/blogs/McFateM`)"
      traefik.http.routers.blog.middlewares: "blog-stripprefix"
      traefik.http.routers.blog.service: "blogsMcFateM-blogs-mcfatem"
      traefik.http.middlewares.blog-stripprefix.stripprefix.prefixes: "/blogs/McFateM"
      traefik.http.routers.blog.entrypoints: "websecure"
      traefik.http.routers.blog.tls: "true"
      com.centurylinklabs.watchtower.enable: "true"

networks:
  proxy:
    external: true
